# Generated by Django 4.0 on 2021-12-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
