# Generated by Django 3.2.6 on 2021-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_active',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='newuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
