# Generated by Django 4.0 on 2021-12-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_price', models.IntegerField(default=700)),
                ('double_price', models.IntegerField(default=500)),
                ('single_price', models.IntegerField(default=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
        migrations.DeleteModel(
            name='RoomSize',
        ),
        migrations.AddField(
            model_name='customer',
            name='price_per_night',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprice'),
        ),
    ]
