# Generated by Django 4.0 on 2021-12-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_roomtype_price_per_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprice',
            old_name='suite_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='double_price',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='single_price',
        ),
    ]
