# Generated by Django 3.2.6 on 2022-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220107_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(to='users.Room'),
        ),
    ]
