# Generated by Django 4.0 on 2021-12-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.room')),
            ],
            bases=('users.room',),
        ),
        migrations.CreateModel(
            name='SingleRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.room')),
            ],
            bases=('users.room',),
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.room')),
            ],
            bases=('users.room',),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_beds',
            field=models.IntegerField(default=1),
        ),
    ]
