# Generated by Django 4.0 on 2021-12-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doubleroom_singleroom_suite_room_number_of_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.roomprice'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
