# Generated by Django 3.2.6 on 2021-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_room_room_type_room_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.IntegerField(default=1),
        ),
    ]
