# Generated by Django 3.2.6 on 2021-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211217_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number_of_beds',
            new_name='number_of_adult_beds',
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_children_beds',
            field=models.IntegerField(default=1),
        ),
    ]
